### ISSUE TITLE
Getting fs.readFileSync warning while building the project

### ISSUE THREAD

**Issue by patelvarun** [hupe1980/gatsby-plugin-webfonts#19]
warn WebpackError: Unsafe builtin usage fs.readFileSync
    at wowe/node_modules/gatsby-plugin-webfonts/gatsby-ssr.js:37:28
    at wowe/.cache/api-runner-ssr.js:53:41
    at wowe/.cache/api-runner-ssr.js:48:25
    at wowe/.cache/static-entry.js:270:5

  35 |       options = (0, _objectWithoutPropertiesLoose2["default"])(_createOptions, ["usePreload", "formats"]);
  36 |
> 37 |   var css = _fs["default"].readFileSync(_path["default"].join("./.cache", "webfonts", "webfonts.css"), "utf8");
     |                            ^
  38 |
  39 |   setHeadComponents([_react["default"].createElement(_preconnect["default"], {
  40 |     key: "webFontsPreconnectGoogleFonts",

**Comment by hupe1980** [comment]
Have a look at #17
