### ISSUE TITLE
self hosted fonts not respecting gatsby "pathPrefix" config

### ISSUE THREAD

**Issue by nkuehn** [hupe1980/gatsby-plugin-webfonts#2]
When building our gatsby site to be hosted in a prefixed path, the webfont asset URLs  in both the preload tags and the CSS are not prefixed and therefore do not load in the production deployment. 

The config and build commands are documented here: https://www.gatsbyjs.org/docs/path-prefix/ 

example output:
```
<style>
      @font-face {
        font-family: Roboto;
        font-style: normal;
        font-weight: 400;
        font-display: swap;
        src: local("Roboto"), local("Roboto-Regular"),
          url(/static/webfonts/s/roboto/v20/KFOmCnqEu92Fr1Mu7GxK.woff2)
            format("woff2"),
          url(/static/webfonts/s/roboto/v20/KFOmCnqEu92Fr1Mu7GxM.woff)
            format("woff"),
          url(/static/webfonts/s/roboto/v20/KFOmCnqEu92Fr1Mu7GxMKTU1Kg.woff)
            format("woff"),
          url(/static/webfonts/s/roboto/v20/KFOmCnqEu92Fr1Mu7GxP.ttf)
            format("truetype");
      }
```

would have to have `/blog/static/webfonts/s/roboto/v20/KFOmCnqEu92Fr1Mu7GxP.ttf` URLs assuming the pathPrefix is set to `/blog`

It could be that this is the helper function provided by gatsby: https://www.gatsbyjs.org/docs/gatsby-link/#add-the-path-prefix-to-paths-using-withprefix 

Otherwise a really nice plugin that does exactly what's needed and not more, thanks for the contribution!  I'll use cdn fonts for now, so not a hard blocker.

**Comment by hupe1980** [comment]
@nkuehn You're right. Path prefix were not supported yet. I have done it now

**Comment by nkuehn** [comment]
Thank you and sorry for the very late feedback!
