### ISSUE TITLE
support Gatsby v4

### ISSUE THREAD

**Issue by cedricdelpoux** [hupe1980/gatsby-plugin-webfonts#26]
When using **Gatsby v4**, there is this annoying warning message

```
gatsby-plugin-webfonts@2.1.1" has incorrect peer dependency "gatsby@^3.0.0"
```

The plugin works as expected and is already compatible

**Comment by cedricdelpoux** [comment]
I made a PR

**Comment by austinbutler** [comment]
Looks like this was fixed by https://github.com/hupe1980/gatsby-plugin-webfonts/pull/27 and released in https://github.com/hupe1980/gatsby-plugin-webfonts/releases/tag/v2.2.2 so this issue can be closed.
