### ISSUE TITLE
selfHosted generating double slashes in URL

### ISSUE THREAD

**Issue by daniyals14** [hupe1980/gatsby-plugin-webfonts#8]
Hello,

When i try to use the selfHosted option, the URL generated is incorrect and has double slashed in the URL like this

> static/webfonts//s/lato/v16/S6uyw4BMUTPHjx4wXg.woff2

I am also using **assetPrefix** option on compile, works fine when this is disabled

**Comment by daniyals14** [comment]
If i make the following change, it works fine, in utils.js

`return _context4.abrupt("return", (pathPrefix || "") + "/static/webfonts" + pathname);`

**Comment by daniyals14** [comment]
@hupe1980 Ive created a PR, can u pls look into it?

**Comment by hupe1980** [comment]
#9 was merged. Thx!
